home/ckeditor/urls.py
from django.conf.urls import url, include

url(r'^ckeditor/', include('ckeditor_uploader.urls')),

home/urls.py
from django.conf.urls import url
from . import views

app_name= 'home'

urlpatterns = [
    # /
    url(r'^$', views.IndexView, name='index'),

    # /contact/
    url(r'^connect/$', views.ConnectView, name='connect'),

    # /success/
    url(r'^success/$', views.SuccessView, name='success'),

    # /team/
    url(r'^team/$', views.TeamView, name='team'),

    # /news/
    url(r'^news/$', views.NewsView.as_view(), name='news'),

    # /research/
    url(r'^research/$', views.ResearchView.as_view(), name='research'),

    # /news/1/
    url(r'^news/(?P<pk>[0-9]+)/$', views.NewsDetailView.as_view(), name='newsdetail'),

    # /research/1/
    url(r'^research/(?P<pk>[0-9]+)/$', views.ResearchDetailView.as_view(), name='researchdetail'),

]

uicdatascilab/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField

# Create your models here.

class NewsAndUpdate(models.Model):
    POSTER_CHOICES = (
        ('Glenn Paul Gara', 'Glenn Paul Gara'),
        ('Isaiah Evans Villa Abrille', 'Isaiah Evans Villa Abrille'),
        ('Seth Jasper Napalit', 'Seth Jasper Napalit'),
        ('Neil Ivan Palacios', 'Neil Ivan Palacios'),
        ('Christine Joy Busalanan', 'Christine Joy Busalanan'),
        ('Jesmar James Rama', 'Jesmar James Rama'),
        ('Reno Marco Fandiño', 'Reno Marco Fandiño'),
        ('Quinn Ray Anthony Intrepido', 'Quinn Ray Anthony Intrepido'),
        ('Mark Kenneth Jimenez', 'Mark Kenneth Jimenez'),
        ('Arch Renzo Falconi', 'Arch Renzo Falconi'),
        ('Elven Earl Tsuruoka', 'Elven Earl Tsuruoka'),
        ('Nikko Tulang', 'Nikko Tulang'),
        ('Villa Abrille and Co.', 'TANOM Group'),
        ('Napalit and Co.', 'HALANG Group'),
        ('Palacios and Co.', 'Explore Davao Group'),
    )

    CATEGORY_CHOICES = (
        ('News', 'News'),
        ('Update', 'Update'),
        ('Event', 'Event'),
        ('Article', 'Article'),
        ('Project', 'Project'),
    )

    NU_Poster = models.CharField(max_length=100, choices=POSTER_CHOICES, default='Glenn Paul Gara')
    NU_Category = models.CharField(max_length=100, choices=CATEGORY_CHOICES, default='News')
    NU_Title = models.CharField(max_length=250)
    NU_Content = RichTextField()
    NU_Logo = models.FileField()
    NU_Posted = models.DateField(default=datetime.now, blank=True)

    def __str__(self):
        return self.NU_Title + ' - ' + self.NU_Content

class Message(models.Model):
    M_Name = models.CharField(max_length=1000)
    M_Email = models.CharField(max_length=1000)
    M_Message = models.TextField()

    def __str__(self):
        return self.M_Name + ' - ' + self.M_Email

home/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['M_Name', 'M_Email', 'M_Message']
        labels = {'M_Name': '', 'M_Email': '', 'M_Message': ''}

home/views.py
from django.views import generic
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import NewsAndUpdate, Message
from django.views import generic
from django.views.generic import View
from .forms import MessageForm
from django.core.urlresolvers import reverse

def IndexView(request):
    template = 'home/index.html'
    neu = NewsAndUpdate.objects.filter(NU_Category='News') | NewsAndUpdate.objects.filter(NU_Category='Event') | NewsAndUpdate.objects.filter(NU_Category='Update').order_by('-NU_Posted', '-id')
    pa = NewsAndUpdate.objects.filter(NU_Category='Project') | NewsAndUpdate.objects.filter(NU_Category='Article').order_by('-NU_Posted', '-id')
    context = {'n': neu, 'p': pa}
    return render(request, template, context)
'''
    nfilter={
        '{0}__{1}'.format('NU_Category', 'iexact'): 'news',
    }
    news = NewsAndUpdate.objects.filter(**nfilter).order_by('-NU_Posted', '-id')[:1]
    efilter={
        '{0}__{1}'.format('NU_Category', 'iexact'): 'event',
    }
    event = NewsAndUpdate.objects.filter(**efilter).order_by('-NU_Posted', '-id')[:1]
    ufilter={
        '{0}__{1}'.format('NU_Category', 'iexact'): 'update',
    }
    update = NewsAndUpdate.objects.filter(**ufilter).order_by('-NU_Posted', '-id')[:1]
    pfilter={
        '{0}__{1}'.format('NU_Category', 'iexact'): 'project',
    }
    project = NewsAndUpdate.objects.filter(**pfilter).order_by('-NU_Posted', '-id')[:1]
    afilter={
        '{0}__{1}'.format('NU_Category', 'iexact'): 'article',
    }
    article = NewsAndUpdate.objects.filter(**afilter).order_by('-NU_Posted', '-id')[:1]
    context = {'n': news, 'e': event, 'u': update, 'p': project, 'a': article}
    return render(request, template, context)
'''


class NewsView(generic.ListView):
    template_name = 'home/news.html'
    context_object_name = 'all_newsandupdate'

    def get_queryset(self):
        combined_queryset = NewsAndUpdate.objects.filter(NU_Category='News') | NewsAndUpdate.objects.filter(NU_Category='Event') | NewsAndUpdate.objects.filter(NU_Category='Update')
        return combined_queryset.order_by('-NU_Posted', '-id')

class NewsDetailView(generic.DetailView):
    model = NewsAndUpdate
    template_name = 'home/newsdetail.html'

class ResearchView(generic.ListView):
    template_name = 'home/research.html'
    context_object_name = 'research'

    def get_queryset(self):
        combined_queryset = NewsAndUpdate.objects.filter(NU_Category='Project') | NewsAndUpdate.objects.filter(NU_Category='Article')
        return combined_queryset.order_by('-NU_Posted', '-id')

class ResearchDetailView(generic.DetailView):
    model = NewsAndUpdate
    template_name = 'home/researchdetail.html'

def ConnectView(request):
    if request.method == 'POST':
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.save()
            return HttpResponseRedirect(reverse('home:success'))
    else:
        form = MessageForm()

    context = {'form': form}
    return render(request, 'home/connect.html', context)

def TeamView(request):
    return render(request, 'home/team.html')

def SuccessView(request):
    return render(request, 'home/success.html')

'''
class IndexView(generic.ListView):
    template_name = 'home/index.html'
    context_object_name = 'all_newsandupdate'

    def get_queryset(self):
        nufilter = {
            '{0}__{1}'.format('NU_Category', 'iexact'): 'project',
        }
        return NewsAndUpdate.objects.exclude(**nufilter).order_by('-NU_Posted', '-id')

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)

        pfilter = {
            '{0}__{1}'.format('NU_Category', 'iexact'): 'project',
        }
        context['project'] = NewsAndUpdate.objects.filter(**pfilter).order_by('-NU_Posted', '-id')
        return context
'''

'''
class ConnectView(generic.ListView):
    template_name = 'home/connect.html'
    context_object_name = 'all_newsandupdate'

    def get_queryset(self):
        return NewsAndUpdate.objects.all().order_by('id')
'''

home/ckeditor/templates/ckeditor/widget.html
{% load static %}
<div class="django-ckeditor-widget" data-field-id="{{id}}" style="display: inline-block;">
    <textarea{{ final_attrs }} data-processed="0" data-config="{{ config }}" data-external-plugin-resources="{{ external_plugin_resources }}" data-id="{{id}}" data-type="ckeditortype">{{ value }}</textarea>
</div>

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>{% block title %}UIC Data Science Laboratory{% endblock %}</title>
<!-- Loads the path to your static files -->
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'home/css/materialize.css' %}" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
  <!-- custom -->


   <!-- animate -->
    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <!-- animate -->
    <link rel="stylesheet" href="{% static 'home/css/animate.min.css' %}">
     <!-- font-awesome -->
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">
    <!-- font-awesome -->
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">
       <!-- favicon -->
     <link rel="icon" type="image/png" href="{% static 'home/images/favicon.png' %}">





  <!--  Scripts-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="{% static 'home/js/materialize.min.js' %}"></script>

      <script type="text/javascript">

        $(document).ready(function () {
    // Plugin initialization
    $('.slider').slider({full_width:false,indicators:true,height:700,transition:300,interval:6000});
        })



        $(document).ready(function(){
    $('.scrollspy').scrollSpy();
  });
       $(document).ready(function(){
    $('.materialboxed').materialbox();
  });

      </script>

  <script src="{% static 'home/js/init.js' %}"></script>


  <!-- wow -->
    <script src="{% static 'home/js/wow.min.js' %}"></script>
    <!-- smoothScroll -->
    <script src="{% static 'home/js/smoothscroll.js' %}"></script>
    <!--fadeout-->
     <script src="{% static 'home/js/fadeout.js' %}"></script>





</head>

<body  data-spy="scroll" data-offset="50" data-target=".navbar-collapse">
<div style="position:absolute;z-index: 5;width: 100%;padding-top:0;">
  <nav class="nav-strip transparent z-depth-0 " role="navigation" style="height: 140px;">
    <div class="nav-wrapper" style="margin-left: 30px;">
    <a id="logo-container" href="{% url 'home:index' %}" class="brand-logo "><img id="logo" src="{% static 'home/images/logo-new.png' %}" class="responsive-img" style="max-height:90%;max-width: 90%;"></a>
    <!--   Navbar Section   -->

   <div class="row"  style="margin-right:120px;">
      <div class="col s12 m12 l12 " style="margin-top: 40px;">
      <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'home:connect' %}" class="make-pink-text" id="contactus"  style="font-size:20px;font-weight:normal;">Connect with us</a></li>
      </ul>
       <ul class="right hide-on-med-and-down ">
        <li><a href="{% url 'home:team' %}" class="make-pink-text" id="team2"  style="font-size:20px;font-weight:normal;">What we do</a></li>
      </ul>
       <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'home:research' %}" class=" make-pink-text" id="research"  style="font-size:20px;font-weight:normal;">Our work</a></li>
      </ul>
       <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'home:news' %}" class=" make-pink-text dropdown-button" id="news" style="font-size:20px;font-weight:normal;">News and updates</a></li>
      </ul>

      </div>

  </div>


   <!--   Sidebar Section   -->
    <div class="container">
      <ul id="nav-mobile" class="side-nav container sidenav-overlay">
      <li><a href="{% url 'home:index' %}">Home</a></li>
        <li><a href="{% url 'home:news' %}">News and Updates</a></li>
          <li><a href="{% url 'home:research' %}">Our Work</a></li>
            <li><a href="{% url 'home:team' %}">What we do</a></li>
              <li><a href="{% url 'home:connect' %}">Connect with us</a></li>
      </ul>

       <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons make-pink-text">menu</i></a>
    </div>
    <!--   End Sidebar Section   -->



</div>
  </nav>
  </div>
  <!--   End Navbar Section   -->
{% block body %}
{% endblock %}

<!--footer-->
   <div class="section make-pink-text" style="margin-top:90px; background-color:#F8F8F8">
      <div class="row ">
      <div class="row left container" style="margin-left:30px;">

      <div class="col s12 m12 l6 left">
                <div class="col s10 make-white-text">
           <h3 style="font-family: Arial;font-weight: bold;font-size: 25px;" class="make-pink-text">Contact</h3>

          <h5 style="font-size: 15px;font-family: Arial;" class="make-pink-text"><a href="https://www.facebook.com/uicdatascience/">datascience@uic.edu.ph</a></h5><br>


      <p class="make-pink-text">2nd Floor, Immaculate Conception Bldg.<br>University of the Immacualte Conception<br>Fr. Selga Street, Davao City</p>

                    </div>
          <div class="col s2 pull-s1">
           <h3 style="font-family: Arial;font-weight: bold;font-size: 25px;" class="make-pink-text">Follow</h3>
                <div class="col s6 " >
          <span style=""><a href="https://www.facebook.com/uicdatascience/"><i class="fa fa-2x fa-facebook" aria-hidden="true"></i></a></span>
          </div>
          <div class="col s6  ">
                    <span><a href="https://www.twitter.com/ayesahyah/"><i class="fa fa-2x fa-twitter" aria-hidden="true"></i></a></span>
          </div>
          </div>
 </div>


      <div class="col s6 push-s6" style="margin-top:35px">
          <div class="col s6 push-s2">
        <img src="{% static 'home/images/uicnewlogo.png' %}" style="height:160px; width:190px">
              </div>
                    <div class="col s6">
          <img src="{% static 'home/images/dallogo.png' %}" style="height:155px; width:155px">
                    </div>
      </div>


     </div>
    </div>
    </div>
    <footer class="page-footer make-pink" style="height: 70px;">
          <div class="container">
            <div class="row">
              <div class="col l6 s12 pull-l2  ">
                <span class="white-text" style="margin-right: 4px;"><a href="{% url 'home:news' %}" class="make-white-text">News and Updates |
                </a></span>
                 <span class="white-text" style="margin-right: 4px;"><a href="{% url 'home:research' %}" class="make-white-text">Our Work |</a></span>
                  <span class="white-text" style="margin-right: 4px;"><a href="{% url 'home:team' %}" class="make-white-text">What we do |</a></span>
                   <span class="white-text" ><a href="{% url 'home:connect' %}" class="make-white-text">Connect with Us</a></span>

              </div>
              <div class="col l4 offset-l2 s12 push-l2">
                 <span class="make-white-text">Copyright <a class="make-white-text" href="">UIC Data Science Laboratory 2017</a></span>
              </div>
            </div>
          </div>

        </footer>

    <!-- end footer -->
</body>
</html>

home/templates/home/connect.html
{% extends 'home/base.html' %}
{% block title %}Connect With Us{% endblock %}
{% load staticfiles %}
{% block body %}
  <br><br><br><br><br><br><br>
<!-- start contact -->
    <div class="col s12 valign-wrapper contact-banner" style="height: 200px;width: 100%;">
        <h1 class="make-white-text center-align" style="margin-left: 100px;">Contact</h1>
    </div>
  <br><br>

    <!-- start contact -->

      <div  class="container">

        <div class="row">
          <div class="col s12 m12 l12 center-align">
        <span class="make-blue-text make-header" >Talk to</span>

        <span class="make-header make-pink-text">us</span>

        <h6 class="container blue-grey-text text-darken-4" >We'd love to hear it from you
         </h6>
         <br><br>
        </div>

      <div class="col s12 contact-bg">
        <div class="col s12 offset-s2 wow fadeInLeft" data-wow-delay="0.6s">
            <h2 class="make-white-text"><strong class="make-white-text">UIC</strong> Data Science Laboratory</h2>


          </div>

          <div class="col s12 " >
          <form action="{% url 'home:connect' %}" method="post" class="" id="contact-form" role="form">
              {% csrf_token %}
              <div class="col s12     wow fadeIn" data-wow-delay="0.3s">
                <input name="{{ form.M_Name.name }}" type="text" class="form-control " id="id_{{ form.M_Name.name }}" placeholder="Name">
                  <label for="id_{{ form.M_Name.name }}">{{ form.M_Name.label }}</label>
              </div>
              <div class="col s12    wow fadeIn" data-wow-delay="0.3s">
                <input name="{{ form.M_Email.name }}" type="email" class="form-control" id="id_{{ form.M_Email.name }}" placeholder="Email">
                  <label for="id_{{ form.M_Email.name }}">{{ form.M_Email.label }}</label>
              </div>
              <div class="col s12   wow fadeIn" data-wow-delay="0.9s" >
                <textarea name="{{ form.M_Message.name }}"   class="form-control" id="id_{{ form.M_Message.name }}" placeholder="Message"   ></textarea>
                  <label for="id_{{ form.M_Message.name }}">{{ form.M_Message.label }}</label>
              </div>

              <div class="col s6  wow fadeIn" data-wow-delay="0.3s" style="padding-bottom: 40px;">
              <br><br>
               <button class="btn waves-effect waves-light make-pink" type="submit" name="action" >Submit
                   <i class="material-icons right make-white-text">send</i>
                        </button>
              </div>
          </form>
          </div>
        </div>
        </div>
      </div>

    <!-- end contact -->
{% endblock %}

<!--
{% load wysiwyg %}
{% wysiwyg_setup %}

<textarea id="foo"></textarea>

{% wysiwyg_editor "foo" %}
-->

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block body %}


  <!--SLider-->

 <div class="slider" id="sliderS" style="">


  <div class="col s12" >

    <ul class="slides" >

      <li>

        <img src="{% static 'home/images/uicdatasciencelab.jpg' %}" >
        <div class="caption center-align" style="margin-top: 100px;">
          <h1 class="wow fadeInDown make-white-text center-align flow-text" data-wow-delay="2000" style="font-size: 70px;margin-top: 100px;">Welcome to</h1>
                <h2 class="wow fadeInDown" data-wow-delay="2000">
                    <span style="font-size: 70px;" >UIC Data Science Laboratory</span></h2>
          <h5 class="light make-white-text">we are the 1st in Mindanao</h5>

        </div>
      </li>

          {% for newsandupdate in n|slice:":1" %}
      <li class="slider-bg" style="background-image: url({{ newsandupdate.NU_Logo.url }}">


      <div class=" center" id="service" style="height: 100%;">
            <div class="caption center-align" style="margin-top: 100px;">
          <h4 class="wow fadeInDown make-white-text center-align flow-text" data-wow-delay="2000" style="font-size: 50px;margin-top: -50px;text-shadow: 2px 2px #04597A;">Be Informed with the current happenings</h4>
                <h2 class="wow fadeInDown" data-wow-delay="2000">
                    <h6 style="font-size: 20px;text-shadow: 2px 2px #04597A;" >Catch the latest news, updates, events, and articles concerning the lab.</h6></h2>
          <!--<h5 class="light make-white-text">we are the 1st in Mindanao</h5>-->

        </div>

      <div class="row">
      <!-- header -->


         <!--news and updates-->

                    <div class="container"  >


              <!--<div class="card-image col s6" style="width:300px;height:300px;margin-top:300px;margin-left:15    0px;">-->
            <!--<img src="{{ newsandupdate.NU_Logo.url }}" >-->
              <!--</div>-->
                        <div class="col s12 center"  style="margin-top:300px;">
            <div class="white-text ">
            <span class="" style="text-shadow: 2px 2px #04597A;font-size:50px;"><b><i><u>Latest {{ newsandupdate.NU_Category }}: {{ newsandupdate.NU_Title }}</u></i></b></span>
              <p class="center" style="text-shadow: 2px 2px #04597A;font-size:20px;"><b>{{ newsandupdate.NU_Category }} posted on {{ newsandupdate.NU_Posted }}.</b></p>
            </div>
            <div class="">

                <a class="waves-effect waves-light btn grey-text text-lighten-5 make-blue"  href="{% url 'home:newsdetail' newsandupdate.id %}" class="grey-text text-lighten-5" style="text-shadow: 2px 2px #04597A;font-size:20px;">Read more</a>

            </div>

                        </div>


        </div>
                              {% endfor %}

      </div>

  </div>

      </li>
        {% for newsandupdate in p|slice:":1" %}
      <li class="slider-bg" style="background-image: url({{ newsandupdate.NU_Logo.url }})">
          <div class="caption center-align" style="margin-top: 100px;">
          <h4 class="wow fadeInDown make-white-text center-align flow-text" data-wow-delay="2000" style="font-size: 50px;margin-top: -50px;text-shadow: 2px 2px #04597A;">Our Work</h4>
                <h2 class="wow fadeInDown" data-wow-delay="2000">
                    <h6 style="font-size: 20px;text-shadow: 2px 2px #04597A;" >Take a look at the featured research,or browse some more</h6></h2>
          <!--<h5 class="light make-white-text">we are the 1st in Mindanao</h5>-->

        </div>

        <!-- start our work -->
         <div class="center" id="project" style="height: 100%;">

      <div class="row">
      <!-- header -->


         <!--our work-->

                    <div class="container"  >


              <!--<div class="card-image col s6" style="width:300px;height:300px;margin-top:300px;margin-left:15    0px;">-->
            <!--<img src="{{ newsandupdate.NU_Logo.url }}" >-->
              <!--</div>-->
                        <div class="col s12 center"  style="margin-top:300px;">
            <div class="white-text ">
            <span class="" style="text-shadow: 2px 2px #04597A;font-size:50px;"><b><i><u>Latest {{ newsandupdate.NU_Category }}: {{ newsandupdate.NU_Title }}</u></i></b></span>
              <p class="center" style="text-shadow: 2px 2px #04597A;font-size:20px;"><b>{{ newsandupdate.NU_Category }} posted on {{ newsandupdate.NU_Posted }}.</b></p>
            </div>
            <div class="">

                <a class="waves-effect waves-light btn grey-text text-lighten-5 make-blue"  href="{% url 'home:newsdetail' newsandupdate.id %}" class="grey-text text-lighten-5" style="font-size:20px;">Read more</a>

            </div>

                        </div>


        </div>
                              {% endfor %}

      </div>




      </li>

      <li class="news-bg">
         <!-- start what we do -->

  <div class="no-pad-bot " id="team-2">

      <div class="row">
      <!-- header -->
        <div class="col s12 m12 l12 center-align " style="margin-top: 130px;text-shadow: 2px 2px #04597A;">
        <span class="make-white-text make-header" >What we </span>

        <span class="make-header make-white-text">do</span>

        <h6 class="container make-white-text" style="font-size: 25px;text-shadow: 2px 2px #04597A;">See the lab ,and get to know the team behind it.
         </h6>

        </div>

        </div>


          <div class="row" >
          <div class=" container" id="lab-banner">
          <div class=" col s6 team-container" >

          <img  src="{% static 'home/images/lab-bg.jpg' %}" >

              <div class="overlay"></div>
                  <div class="button"><a href="{% url 'home:team' %}">SEE THE LAB</a></div>

          </div>
          <div class="col s6 team-container" id="team-banners" >

          <img   src="{% static 'home/images/team-banner.jpg' %}" >
           <div class="overlay"></div>
                  <div class="button"><a href="{% url 'home:team' %}">MEET THE TEAM</a></div>

          </div>


         </div>
         <div style="height: 400px;width: 100%;"></div>
          </div>




  </div>
   <!--   End of what we do  -->
      </li>

    </ul>
    </div>
  </div>





{% endblock %}

home/templates/home/news.html
{% extends 'home/base.html' %}
{% block title %}News And Updates{% endblock %}
{% load staticfiles %}
{% block body %}
  <br><br><br><br><br><br><br>
    <!-- start news -->
    <div class="col s12 m12 l12  valign-wrapper news-banner" style="height: 200px;width: 100%;">
        <h1 class="make-white-text center-align" style="margin-left: 100px;">News and Updates</h1>
    </div>

     <div class="row container">


    {% if all_newsandupdate %}
            {% for newsandupdate in all_newsandupdate %}
         <div class="col s12 m4 l4">
            <div class="card  medium" id="news-card">
              <div class="card-image">
            <img src="{{ newsandupdate.NU_Logo.url }}" width="200" height="200">
            <span class="card-title" style="text-shadow: 2px 2px #04597A;"><b><i><u>{{ newsandupdate.NU_Title }}</u></i></b></span>
              </div>
            <div class="card-content white-text">
              <p class="container"><b>{{ newsandupdate.NU_Category }} posted on {{ newsandupdate.NU_Posted }}.</b> <br>{{ newsandupdate.NU_Content|safe|slice:":143" }}...</p>
            </div>
            <div class="card-action">
              <a href="{% url 'home:newsdetail' newsandupdate.id %}">Read More</a>

            </div>
          </div>

        </div>
            {% endfor %}
    {% else %}
        <h3>We don't have any News and or Updates as of now...</h3>
    {% endif %}

      </div>
    <!-- end news -->

{% endblock %}

home/templates/home/research.html
{% extends 'home/base.html' %}
{% block title %}Our Work{% endblock %}
{% load staticfiles %}
{% block body %}
  <br><br><br><br><br><br><br>
		<!-- start research -->
		<div class="col s12 research-banner valign-wrapper " style="height: 200px;width: 100%;">
				<h1 class="make-white-text center-align" style="margin-left: 100px;">Research</h1>
		</div>

		<div class="row container">


    {% if research %}
            {% for newsandupdate in research %}
          <div class="col s12 m4 l4">
            <div class="card  medium blue-grey darken-1" id="news-card">
              <div class="card-image">
            <img src="{{ newsandupdate.NU_Logo.url }}" width="200" height="200">
            <span class="card-title" style="text-shadow: 2px 2px #04597A;"><b><i><u>{{ newsandupdate.NU_Title }}</u></i></b></span>
              </div>
            <div class="card-content white-text">
              <p class="container"><b>{{ newsandupdate.NU_Category }} posted on {{ newsandupdate.NU_Posted }}.</b> <br>{{ newsandupdate.NU_Content|safe|slice:":143" }}...</p>
            </div>
            <div class="card-action">
              <a href="{% url 'home:researchdetail' newsandupdate.id %}">Read More</a>

            </div>
          </div>

        </div>
            {% endfor %}
    {% else %}
        <h3>We don't have any Research articles as of now...</h3>
    {% endif %}

      </div>
    <!-- end news -->

{% endblock %}